---
- name: Ensure GitLab data directory exists
  file:
    path: "{{ gitlab_data_directory }}"
    state: directory
    owner: 998
    group: 998
    mode: '0750'
  become: yes

- name: Create GitLab directory
  file:
    path: "/home/{{ ansible_user }}/gitlab"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Copy docker-compose.yml for GitLab
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ ansible_user }}/gitlab/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: '0644'

- name: Start GitLab using Docker Compose
  docker_compose:
    project_src: "/home/{{ ansible_user }}/gitlab"
    state: present
