---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default Nginx site configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Deploy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/reverse_proxy.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable Nginx reverse proxy configuration
  file:
    src: /etc/nginx/sites-available/reverse_proxy.conf
    dest: /etc/nginx/sites-enabled/reverse_proxy.conf
    state: link

- name: Test Nginx configuration
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc != 0

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
