---
- name: Ensure OwnCloud data directory exists
  file:
    path: "{{ owncloud_data_directory }}"
    state: directory
    owner: "{{ owncloud_uid }}"
    group: "{{ owncloud_gid }}"
    mode: '0750'
  become: yes

- name: Adjust ownership of OwnCloud data directory
  file:
    path: "{{ owncloud_data_directory }}"
    owner: "{{ owncloud_uid }}"
    group: "{{ owncloud_gid }}"
    recurse: yes
  become: yes

- name: Create OwnCloud directory
  file:
    path: "/home/{{ ansible_user }}/owncloud"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Copy docker-compose.yml for OwnCloud
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ ansible_user }}/owncloud/docker-compose.yml"
    owner: "{{ ansible_user }}"
    mode: '0644'

- name: Start OwnCloud using Docker Compose
  docker_compose:
    project_src: "/home/{{ ansible_user }}/owncloud"
    state: present
